### ISSUE TITLE
Can not deploy Resa on latest dokku version

### ISSUE THREAD

**Issue by hugnata** [BdEINSALyon/resa#10]
Unable to deploy Resa on a Dokku server, find a log here: https://gist.github.com/anonymous/aebbfe2f15b91a447c7c938792c84995
Edit:
I was thinking that  the problem was link with the aplication but it's link to Dokku (mb). Did the application need special libraries to work ?

**Comment by Crocmagnon** [comment]
We'll use vanilla Docker.
