### ISSUE TITLE
"Occurrences" peu clair

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/resa#45]
Remplacer "occurrences" par "réservations".

**Comment by Crocmagnon** [comment]
Qu'est-ce qu'on affiche à la place de "Réservation" ?

**Comment by Crocmagnon** [comment]
On ne change pas.

**Comment by Crocmagnon** [comment]
Ça pose des problèmes dans certaines constructions :
"Êtes-vous certain de vouloir supprimer la réservation suivante ? Toutes les occurrences liées seront supprimées."

**Comment by JulesSaada** [comment]
Remplacer "Réservation" par "Modèle de réservation" ? (ce n'est pas une réservation en soi, plus un conteneur auquel tu vas associer des réservations effectives)
"Êtes-vous certain de vouloir supprimer le modèle de réservation suivant ? Toutes les réservations liées seront supprimées."
