### ISSUE TITLE
Problème de connexion à l'interface d'administration

### ISSUE THREAD

**Issue by Crocmagnon** [BdEINSALyon/resa#68]
Les utilisateurs des groupes Azure ne sont plus autorisés à se connecter à l'interface d'administration.

**Comment by JulesSaada** [comment]
C koi lé groupe Azure ?

**Comment by JulesSaada** [comment]
Au final, qui a accès à l'interface admin ? On avait dit qu'on limitait ça au Resp Services + OrgaIf pour que les soucis de modifications inapropriées remontent par la même personne.

**Comment by Crocmagnon** [comment]
Actuellement, Bureau + Orgaif. Mais ça se règle par groupes Sharepoint donc on peut faire ce qu'on veut. À mon sens c'est pas idiot, ça limite suffisamment sans être bloquant s'il y a un problème à résoudre.
Le Resp VA doit aussi y avoir accès pour le matos Pool des assos ;)

**Comment by JulesSaada** [comment]
A mon sens c'est trop, on a trop vu cette année de modifs (papier du coup, mais ça doit disparaitre à terme) qui sont faites avec une bonne volonté certes mais par des gens qui n'ont pas toutes les infos et ça bloque des choses derrière que le mec qui gère le matos (donc le resp Services ou VA) doit rattraper un peu comme il peut et si on peut éviter cette gmq en amont c'est quand même mieux.
Du coup pour moi il faut limiter Services + VA (shame on me je l'avais oublié ! Répète pas ;) )

**Comment by Crocmagnon** [comment]
C'est faisable dans tous les cas 😉

**Comment by JulesSaada** [comment]
Du coup à faire :)

**Comment by Crocmagnon** [comment]
Il faut corriger le problème suivant :
Soient les groupes Azure `A` et `B` et le groupe Django `C`. Soient les relations suivantes : `A -> C` et `B -> C`.
Soit l'utilisateur `u` appartenant au groupe `A` mais pas au groupe `B`.
Alors, le système de gestion des permissions ajoutera `u` au groupe `C` (à cause de l'appartenance à `A`) puis l'enlèvera du groupe (à cause de la non appartenance à `B`).
`u`, qui devrait alors avoir accès au groupe `C`, ne l'a pas.
